<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>CS8600;CS8602;CS8603;</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Domain\Safes\" />
    </ItemGroup>

</Project>
